---
- cando: identity-management/actors.deleter
  title: Allows deletion of actors
  description: Required to be able to delete actors
- cando: identity-management/actors.reader
  title: Can read the REST interface for actors
  description: Only overview listing and single actor details
- cando: identity-management/actors.writer
  title: Can write the REST interface for actors
  description: Can read, create new and update or destroy existing actors
- cando: identity-management/app-tenant.admin
  title: Tenant Administrator
  description: Required as base to administrate this app's tenants
- cando: identity-management/apps.admin
  title: App Administrator
  description: Required as base to administrate app settings
- cando: identity-management/apps.deleter
  title: Allows deletion of apps
  description: Required to be able to delete apps
- cando: identity-management/apps.reader
  title: Can read the REST interface for apps
  description: Only overview listing and single app details
- cando: identity-management/apps.writer
  title: Can write the REST interface for apps
  description: Can read, create new and update or destroy existing apps
- cando: identity-management/contents.deleter
  title: Allows deletion of contents
  description: Required to be able to delete actors
- cando: identity-management/contents.reader
  title: Can read the REST interfac of contents
  description: Only overview listing and single content details
- cando: identity-management/contents.writer
  title: Can write the REST interface for contents
  description: Can read, create new and update or destroy existing contents
- cando: identity-management/email-blacklists.deleter
  title: Allows deletion of email-blacklists
  description: Required to be able to delete email-blacklists
- cando: identity-management/email-blacklists.reader
  title: Can read the REST Interface for email blacklists
  description: Only overview listing and display domains for email blacklisting
- cando: identity-management/email-blacklists.writer
  title: Can write the REST interface for email blacklists
  description: Can read, create new and update or destroy existing domains for email
    blacklisting
- cando: identity-management/functionalities.deleter
  title: Allows deletion of functionalities
  description: Required to be able to delete functionalities
- cando: identity-management/functionalities.reader
  title: Can read the REST interface for functionalities
  description: Only overview listing and single functionality details
- cando: identity-management/functionalities.writer
  title: Can write the REST interface for functionalities
  description: Can read, create new and update or destroy existing functionalities
- cando: identity-management/global.admin
  title: Global Admin
  description: Required as base to administrate things like E-Mail Blacklisting
- cando: identity-management/global-tenant.admin
  title: Global tenant admin
  description: Can administrate all tenants
- cando: identity-management/list-tenant-users.reader
  title: Show and search users
  description: Allows displaying users assigned to groups
- cando: identity-management/list-tenant-users.writer
  title: Assign users to a group
  description: Allows adding users to a group or remove them
- cando: identity-management/roles.deleter
  title: Allows deletion of roles
  description: Required to be able to delete roles
- cando: identity-management/roles.reader
  title: Can read the REST Interface for roles
  description: Only overview listing and single role details
- cando: identity-management/roles.writer
  title: Can write the REST interface for roles
  description: Can read, create new and update or destroy existing roles
- cando: identity-management/tenant.admin
  title: Tenant Administrator
  description: Required as base to administrate this app's tenants
- cando: identity-management/tenant.deleter
  title: Allows deletion of tenants
  description: Required to be able to delete tenant actors
- cando: identity-management/tenant.reader
  title: Can read the REST interface for tenants
  description: Only overview listing and single tenants details
- cando: identity-management/tenant.writer
  title: Can write the REST interface for tenants
  description: Can read, create new and update or destroy existing tenants
- cando: identity-management/tenant-users.picker
  title: Can read the REST interface to list/paginate users of a specified tenant
  description: Can read the REST interface to list/paginate users of a specified tenant
    for User pickers if the authenticated user is member of that tenant
- cando: identity-management/tenants.admin
  title: Tenant Administrator
  description: Required as base to administrate this app's tenants
- cando: identity-management/tenants.deleter
  title: Allows deletion of tenants
  description: Required to be able to delete tenant actors
- cando: identity-management/tenants.reader
  title: Can read the REST interface for tenants
  description: Only overview listing and single tenants details
- cando: identity-management/tenants.writer
  title: Can write the REST interface for tenants
  description: Can read, create new and update or destroy existing tenants
- cando: identity-management/users.deleter
  title: Allows deletion of users
  description: Required to be able to delete users
- cando: identity-management/users.reader
  title: Can read the REST interface for users
  description: Only overview listing and single user details
- cando: identity-management/users.writer
  title: Can write the REST interface for users
  description: Can read, create new and update or destroy existing users
